### ISSUE TITLE
Is docker image for Apple silicon ARM64 available?

### ISSUE THREAD

**Issue by mkazanov** [HKU-BAL/Clair3-RNA#3]
Is docker image for Apple silicon ARM64 available?

**Comment by aquaskyline** [comment]
the image itself is Linux-64 only, but you can run it in Apple silicon under docker virtualization. Most of the cases run to the end. Some samples failed with 'illegal instructions' or 'segmentation fault', which might probably be fixed in the future version of docker on mac.

**Comment by mkazanov** [comment]
I've tried to run it inside the virtual Linux machine (via Parallels) but got the following error:
```
sudo docker run -it -v /disk2t/DATA/input:/disk2t/DATA/input -v /disk2t/DATA/output:/disk2t/DATA/output hkubal/clair3-rna:latest /opt/bin/run_clair3_rna --bam_fn /disk2t/DATA/input/E1051.bam --ref_fn /disk2t/DATA/input/ref.fna --threads 10 --platform ont_guppy_drna002 --output_dir /disk2t/DATA/output
[sudo] password for parallels: 
Unable to find image 'hkubal/clair3-rna:latest' locally
latest: Pulling from hkubal/clair3-rna
35b42117c431: Pull complete 
ad9c569a8d98: Pull complete 
293b44f45162: Pull complete 
0c175077525d: Pull complete 
3f833affc2d1: Pull complete 
9d9752cc50a8: Pull complete 
5022e0189971: Pull complete 
236854f56c52: Pull complete 
c0c9808a4282: Pull complete 
Digest: sha256:f490d92a8ff02617aae7377d5395fc2204e518036176f5aa22d0ab8fdf8e8168
Status: Downloaded newer image for hkubal/clair3-rna:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /opt/bin/run_clair3_rna: exec format error
```

**Comment by aquaskyline** [comment]
If you try `uname -a` in your virtual Linux machine via Parallels it might be showing arm64, which means that you've installed arm64 linux, not amd64.

Please try using MacOS native docker.

**Comment by corrosive4354** [comment]
There are already too many compatibility issues between Docker and Arm64 on the Internet. You can replace Docker with Servbay to deploy the development environment. [Servbay](https://servbay.com) is more professional on Mac.
